# SSL证书管理系统 - 快速部署版本
# 使用预构建的基础镜像，避免网络问题

version: '3.8'

services:
  # SSL证书管理系统基础镜像
  ssl-cert-system-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: ssl-cert-system-base:latest
    container_name: ssl-cert-system-base-fast

  # SSL证书管理系统 - Go版本 (快速部署)
  ssl-cert-system:
    # 使用基础镜像构建应用
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        VERSION: "1.0.2"
        BUILD_TIME: "${BUILD_TIME:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
        GIT_COMMIT: "${GIT_COMMIT:-$(git rev-parse --short HEAD)}"
    depends_on:
      - ssl-cert-system-base
    # 或者使用预构建的镜像
    # image: ghcr.io/lijh1983/ssl_cert_system:latest
    container_name: ssl-cert-system-go-fast
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      # 远程MySQL数据库配置
      - DB_HOST=${DB_HOST:-8.134.130.92}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-ssl_cert_system}
      - DB_USER=${DB_USER:-ssl_dev}
      - DB_PASSWORD=${DB_PASSWORD:-ssl_manager_password_123}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here_change_in_production}
      - ACME_SERVER=${ACME_SERVER:-https://acme-v02.api.letsencrypt.org/directory}
      - ACME_EMAIL=${ACME_EMAIL:-your_email@domain.com}
      - ACME_STORAGE_PATH=/app/storage/certs
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - APP_VERSION=1.0.2
    volumes:
      - ssl_certs:/app/storage/certs
      - ssl_logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ssl_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx前端服务器
  nginx:
    image: nginx:alpine
    container_name: ssl-nginx-go-fast
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      ssl-cert-system:
        condition: service_healthy
    networks:
      - ssl_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Redis支持已移除 - 当前版本未实现Redis功能

volumes:
  ssl_certs:
    driver: local
  ssl_logs:
    driver: local

networks:
  ssl_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
